# Generated by Django 3.2 on 2021-05-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotAgain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assignment_upload',
            managers=[
            ],
        ),
    ]
