# Generated by Django 3.2 on 2021-05-18 08:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('NotAgain', '0002_alter_assignment_upload_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
