# Generated by Django 3.2 on 2021-05-18 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('NotAgain', '0003_alter_students_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assignment_upload',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='students',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Assignment_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=20, null=True)),
                ('title', models.CharField(default='', max_length=20, null=True)),
                ('upload_date', models.DateField()),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('reference_file', models.FileField(upload_to='media')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
