# Generated by Django 3.2 on 2021-05-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NotAgain', '0007_assignment_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_return',
            name='assign_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NotAgain.assignment_form'),
        ),
    ]
